#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tdb
Version  : 1.3.16
Release  : 9
URL      : https://www.samba.org/ftp/tdb/tdb-1.3.16.tar.gz
Source0  : https://www.samba.org/ftp/tdb/tdb-1.3.16.tar.gz
Summary  : A trivial database
Group    : Development/Tools
License  : LGPL-3.0+
Requires: tdb-bin
Requires: tdb-lib
Requires: tdb-man
Requires: tdb-python
BuildRequires : docbook-xml
BuildRequires : libxml2
BuildRequires : libxml2-dev
BuildRequires : libxslt
BuildRequires : libxslt-dev
BuildRequires : python-core
BuildRequires : python-dev
Patch1: wafwafwaf.patch
Patch2: 0001-add-mock-disable-static-option.patch

%description
See http://code.google.com/p/waf/ for more information on waf
You can get a svn copy of the upstream source with:

%package bin
Summary: bin components for the tdb package.
Group: Binaries
Requires: tdb-man

%description bin
bin components for the tdb package.


%package dev
Summary: dev components for the tdb package.
Group: Development
Requires: tdb-lib
Requires: tdb-bin
Provides: tdb-devel

%description dev
dev components for the tdb package.


%package legacypython
Summary: legacypython components for the tdb package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the tdb package.


%package lib
Summary: lib components for the tdb package.
Group: Libraries

%description lib
lib components for the tdb package.


%package man
Summary: man components for the tdb package.
Group: Default

%description man
man components for the tdb package.


%package python
Summary: python components for the tdb package.
Group: Default

%description python
python components for the tdb package.


%prep
%setup -q -n tdb-1.3.16
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535910194
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1535910194
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/tdbbackup
/usr/bin/tdbdump
/usr/bin/tdbrestore
/usr/bin/tdbtool

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libtdb.so
/usr/lib64/pkgconfig/tdb.pc

%files legacypython
%defattr(-,root,root,-)
%exclude /usr/lib/python2.7/site-packages/_tdb_text.py
%exclude /usr/lib/python2.7/site-packages/tdb.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libtdb.so.1
/usr/lib64/libtdb.so.1.3.16

%files man
%defattr(-,root,root,-)
/usr/share/man/man8/tdbbackup.8
/usr/share/man/man8/tdbdump.8
/usr/share/man/man8/tdbrestore.8
/usr/share/man/man8/tdbtool.8

%files python
%defattr(-,root,root,-)
